// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2022-02-10 12:41:42.038142 -0600 CST m=+0.027363840
package cmd

const GITVERSION = `ad43210 update deps`
const SEMVER = "1.0.0"
const DEPENDENCIES = `module gitlab.com/elixxir/client-registrar

go 1.17

require (
	github.com/jinzhu/gorm v1.9.12
	github.com/mitchellh/go-homedir v1.1.0
	github.com/pkg/errors v0.9.1
	github.com/spf13/cobra v1.1.3
	github.com/spf13/jwalterweatherman v1.1.0
	github.com/spf13/viper v1.7.1
	gitlab.com/elixxir/comms v0.0.4-0.20220128193157-34178165415d
	gitlab.com/elixxir/crypto v0.0.7-0.20220210173208-c88f852c79ca
	gitlab.com/elixxir/registration v1.5.1-0.20220126233506-7a27590195ec
	gitlab.com/xx_network/comms v0.0.4-0.20220126231737-fe2338016cce
	gitlab.com/xx_network/crypto v0.0.5-0.20220209220237-f1e27faab497
	gitlab.com/xx_network/primitives v0.0.4-0.20220209215928-ebad9b1d4f04
	google.golang.org/protobuf v1.27.1
)

require (
	github.com/fsnotify/fsnotify v1.4.9 // indirect
	github.com/golang/protobuf v1.5.2 // indirect
	github.com/gopherjs/gopherjs v0.0.0-20200217142428-fce0ec30dd00 // indirect
	github.com/hashicorp/hcl v1.0.0 // indirect
	github.com/inconshreveable/mousetrap v1.0.0 // indirect
	github.com/jinzhu/inflection v1.0.0 // indirect
	github.com/jinzhu/now v1.1.2 // indirect
	github.com/lib/pq v1.10.2 // indirect
	github.com/magiconair/properties v1.8.1 // indirect
	github.com/mitchellh/mapstructure v1.4.1 // indirect
	github.com/pelletier/go-toml v1.7.0 // indirect
	github.com/spf13/afero v1.2.2 // indirect
	github.com/spf13/cast v1.3.1 // indirect
	github.com/spf13/pflag v1.0.5 // indirect
	github.com/subosito/gotenv v1.2.0 // indirect
	gitlab.com/elixxir/primitives v0.0.3-0.20220209225643-ae03845af237 // indirect
	golang.org/x/crypto v0.0.0-20220209195652-db638375bc3a // indirect
	golang.org/x/net v0.0.0-20211112202133-69e39bad7dc2 // indirect
	golang.org/x/sys v0.0.0-20220209214540-3681064d5158 // indirect
	golang.org/x/text v0.3.6 // indirect
	google.golang.org/genproto v0.0.0-20210315173758-2651cd453018 // indirect
	google.golang.org/grpc v1.44.0 // indirect
	gopkg.in/ini.v1 v1.51.0 // indirect
	gopkg.in/yaml.v2 v2.4.0 // indirect
)
`
