// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2022-10-20 11:58:23.985949 -0500 CDT m=+0.023501678

package cmd

const GITVERSION = `a2b559f update deps`
const SEMVER = "1.1.0"
const DEPENDENCIES = `module gitlab.com/elixxir/client-registrar

go 1.17

require (
	github.com/golang/protobuf v1.5.2
	github.com/jinzhu/gorm v1.9.12
	github.com/mitchellh/go-homedir v1.1.0
	github.com/pkg/errors v0.9.1
	github.com/spf13/cobra v1.1.3
	github.com/spf13/jwalterweatherman v1.1.0
	github.com/spf13/viper v1.7.1
	gitlab.com/elixxir/comms v0.0.4-0.20221017173926-4eaa6061dfaa
	gitlab.com/elixxir/crypto v0.0.7-0.20221017204335-9201b3672f3a
	gitlab.com/elixxir/registration v1.5.1-0.20220308210944-4419d95b9dfc
	gitlab.com/xx_network/comms v0.0.4-0.20221017172508-09e33697dc15
	gitlab.com/xx_network/crypto v0.0.5-0.20221017172404-b384a8d8b171
	gitlab.com/xx_network/primitives v0.0.4-0.20221017171439-42169a3e5c0d
)

require (
	git.xx.network/elixxir/grpc-web-go-client v0.0.0-20220908170150-ef04339ffe65 // indirect
	github.com/cenkalti/backoff/v4 v4.1.3 // indirect
	github.com/desertbit/timer v0.0.0-20180107155436-c41aec40b27f // indirect
	github.com/fsnotify/fsnotify v1.4.9 // indirect
	github.com/gopherjs/gopherjs v0.0.0-20200217142428-fce0ec30dd00 // indirect
	github.com/gorilla/websocket v1.5.0 // indirect
	github.com/hashicorp/hcl v1.0.0 // indirect
	github.com/improbable-eng/grpc-web v0.15.0 // indirect
	github.com/inconshreveable/mousetrap v1.0.0 // indirect
	github.com/jinzhu/inflection v1.0.0 // indirect
	github.com/jinzhu/now v1.1.2 // indirect
	github.com/klauspost/compress v1.11.7 // indirect
	github.com/lib/pq v1.10.2 // indirect
	github.com/magiconair/properties v1.8.1 // indirect
	github.com/mitchellh/mapstructure v1.4.1 // indirect
	github.com/pelletier/go-toml v1.7.0 // indirect
	github.com/rs/cors v1.8.2 // indirect
	github.com/soheilhy/cmux v0.1.5 // indirect
	github.com/spf13/afero v1.2.2 // indirect
	github.com/spf13/cast v1.3.1 // indirect
	github.com/spf13/pflag v1.0.5 // indirect
	github.com/subosito/gotenv v1.2.0 // indirect
	gitlab.com/elixxir/primitives v0.0.3-0.20221017172918-6176818d1aba // indirect
	go.uber.org/atomic v1.10.0 // indirect
	golang.org/x/crypto v0.0.0-20220525230936-793ad666bf5e // indirect
	golang.org/x/net v0.0.0-20220822230855-b0a4917ee28c // indirect
	golang.org/x/sys v0.0.0-20220728004956-3c1f35247d10 // indirect
	golang.org/x/text v0.3.7 // indirect
	google.golang.org/genproto v0.0.0-20220822174746-9e6da59bd2fc // indirect
	google.golang.org/grpc v1.49.0 // indirect
	google.golang.org/protobuf v1.28.1 // indirect
	gopkg.in/ini.v1 v1.51.0 // indirect
	gopkg.in/yaml.v2 v2.4.0 // indirect
	nhooyr.io/websocket v1.8.7 // indirect
)
`
